[tool.poetry]
name = "aoc2024"
version = "0.1.0"
description = ""
authors = ["Aidar Rakhimov <a.rakhimov@cian.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
